### ISSUE TITLE
generalize to arbitrary dimensions

### ISSUE THREAD

**Issue by bhomass** [syrte/ndtest#5]
This code works for 2 dimensions. Can it be expanded to work for arbitrary number of dimensions, like over 100?

**Comment by bhomass** [comment]
Apparently, it would be excessively expensive in computation load when this method is extended further.

**Comment by syrte** [comment]
Agreed. The computation cost will be too high for ND KS test, as it uses quadrants. Also it is unclear how well it works for higher dimensions.
The energy distance statistics test may work. Maybe you can check with literature.
